### ISSUE TITLE
Skating Level 1 - "Previous Lesson" buttons don't match lesson navigation ordering

### ISSUE THREAD

**Issue by russellsmith** [HowToHockey/ThePond#18]
I navigated to Skating Level 1.  The navigation bar on the right shows Stationary Edges as the first lesson in the course.  

When I open the "Stationary Edges" lesson there’s a notification at the bottom of the page telling me to “Please go back and complete the previous lesson.”  There’s also a red "Previous Lesson" button.  

<img width="891" alt="Screen Shot 2020-10-21 at 8 05 58 AM" src="https://user-images.githubusercontent.com/654652/96739088-46ce6e80-1374-11eb-9cf4-98ecb361767e.png">

Both buttons take buttons take me to the Acceleration course which looks like it’s toward the end of the course based on the lesson navigation.

Similarly the "Stationary Crossovers" lesson links to “Arm Swing” lesson as the previous lesson.  The “Arm Swing” lesson links to “Stationary Edges” as the previous lesson. And “Snow Plow Stops” links to “Stationary Crossovers” as the previous lesson.

It seems like what is defining the ordering for the navigation is separate and unaligned with the ordering used for these buttons.

**Comment by russellsmith** [comment]
These bottom page navigation options on the "Skating Level 1" course seems different than others.  Other courses have "Next Lesson" and "Mark as Complete" options at the bottom of each page.  These don't show for me on the "Skating Level 1" lessons.

**Comment by HadenHiles** [comment]
@russellsmith thanks for the detailed issue! This course was recently created by Jeremy and the course settings were configured differently than the rest, also, the lesson order was all messed up lol.

We've updated the course accordingly 👍
