### ISSUE TITLE
Lesson breadcrumb - "Courses" links seems off

### ISSUE THREAD

**Issue by russellsmith** [HowToHockey/ThePond#19]
When viewing a course lesson the "Courses" link does not take you to the Courses page.  Instead it links to the current lesson you're currently looking at.

<img width="341" alt="Screen Shot 2020-10-21 at 8 10 22 AM" src="https://user-images.githubusercontent.com/654652/96740015-471b3980-1375-11eb-8262-aab6aab12863.png">

In this case I was on the "Basic Grip" lesson in "Intro To Stickhandling".  The Course breadcrumb links to "https://thepond.howtohockey.com/lessons/basic-grip/".  Clicking on it just effectively reloads the page you're currently on.

Similarly when on the course overview page "Courses" just links to the current course you're looking at.

The "Dashboard" link at the top of the breadcrumb tree links to "https://thepond.howtohockey.com/?post_type=acf-field&p=253" which shows a 404 error.

**Comment by russellsmith** [comment]
Does that commit also resolve this?

>The "Dashboard" link at the top of the breadcrumb tree links to "https://thepond.howtohockey.com/?post_type=acf-field&p=253" which shows a 404 error.

**Comment by HadenHiles** [comment]
> Does that commit also resolve this?
> 
> > The "Dashboard" link at the top of the breadcrumb tree links to "https://thepond.howtohockey.com/?post_type=acf-field&p=253" which shows a 404 error.

I resolved that in the following commit 59b6728 😄

**Comment by russellsmith** [comment]
My bad! I missed the second commit hash.
