### ISSUE TITLE
Unable to complete "Skating Level 1" lessons

### ISSUE THREAD

**Issue by russellsmith** [HowToHockey/ThePond#21]
None of the lessons in "Skating Level 1" show the "Mark Complete" button with the exception of "Backwards Skating".

<img width="843" alt="Screen Shot 2020-10-21 at 8 28 20 AM" src="https://user-images.githubusercontent.com/654652/96742129-67e48e80-1377-11eb-8277-b95331c69450.png">

On "Backwards Skating" this button is aligned to the right side instead of in the middle where it appears on other course lessons.

**Comment by HadenHiles** [comment]
Resolved with #18
