### ISSUE TITLE
"McDavid In Tight Challenge" allows fractional values

### ISSUE THREAD

**Issue by russellsmith** [HowToHockey/ThePond#22]
It's possible to enter fractional values for this challenge which don't make sense in context of targets hit.  

The "step" on the input is currently "0.01" so it kind of encourages this behavior through the buttons on the input field.  This could be set to step="1" min="1" to encourage whole numbers.  

<img width="474" alt="Screen Shot 2020-10-21 at 8 42 27 AM" src="https://user-images.githubusercontent.com/654652/96743981-64ea9d80-1379-11eb-9144-475ee64c217a.png">

This is probably not worth worrying about.

**Comment by HadenHiles** [comment]
@russellsmith this was actually intentional, because depending on the challenge you could have a time score, or a value score  😃
